name: Simple Usage

on: push


jobs:
  build:
    name: Upload slides
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Pandoc Document Converter
        uses: Ender-events/pandoc@master
        with:
          args: '-s -o README.pdf README.md'
